#!/usr/bin/env bash
launchctl unload -F /System/Library/LaunchAgents/com.apple.WindowManager.plist

source ~/.env_common
source ~/.load_language_envs

yabai -m signal --add event=dock_did_restart 'action=sudo yabai --load-sa'
sudo yabai --load-sa

yabai -m config external_bar                 all:28:0

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
# having issues with window_opacity
yabai -m config window_opacity               off
yabai -m config window_shadow                on
yabai -m config window_border                on
yabai -m config window_border_placement      inset
yabai -m config window_border_width          1
yabai -m config active_window_border_topmost off
yabai -m config active_window_border_color   0xffffffff
yabai -m config normal_window_border_color   0x00000000
yabai -m config insert_window_border_color   0xffd75f5f
yabai -m config active_window_opacity        1
yabai -m config normal_window_opacity        0.90
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  5
yabai -m config bottom_padding               5
yabai -m config left_padding                 5
yabai -m config right_padding                5
yabai -m config window_gap                   5

# creates spaces and labels
yabaictl update-spaces

yabai -m rule --add app="Google Play Music Desktop Player" space=s10
yabai -m rule --add app="System Preferences" manage=off
yabai -m rule --add app="Pritunl" manage=off
yabai -m rule --add app="DBeaver.*" title=".*([Cc]onnect|Preferences|Search|Driver|[Pp]roperties).*)" manage=off
yabai -m rule --add app="Calculator" manage=off
yabai -m rule --add app="Installer" manage=off
yabai -m rule --add app="PluginLauncher" manage=off

yabai -m signal --add event=display_added action='zsh -c "sleep 5; yabaictl update-spaces"'
yabai -m signal --add event=display_removed action='zsh -c "sleep 5; yabaictl update-spaces"'

echo "yabai configuration loaded.."
