#!/bin/bash

# fixes a weird black line on the top of the screen on login
systemctl --user --no-block restart compton
# makes sure backgrounds are updated to match number of monitors
systemctl --user --no-block restart set_wallpaper
# fixes rescuetime icon dissapearing when switching
systemctl --user --no-block restart rescuetime
