#!/bin/bash

# fixes a weird black line on the top of the screen on login
systemctl --user --no-block restart compton
# makes sure backgrounds are updated to match number of monitors
systemctl --user --no-block restart set_wallpaper
# make sure polybar gets moved to the right desktop
# also makes sure rescuetime doesn't dissapear
systemctl --user --no-block restart polybar
